---
apiVersion: v1
kind: Template
labels:
  template: cronjob-ldap-group-sync
objects:
- kind: "ServiceAccount"
  apiVersion: "v1"
  metadata:
    name: "${JOB_SERVICE_ACCOUNT}"
    namespace: "${NAMESPACE}"
- kind: "ClusterRole"
  apiVersion: "rbac.authorization.k8s.io/v1"
  metadata:
    name: "ldap-group-syncer"
    namespace: "${NAMESPACE}"
  rules:
  - apiGroups:
    - ""
    - "user.openshift.io"
    resources:
    - "groups"
    verbs:
    - "get"
    - "list"
    - "create"
    - "update"
- kind: "ClusterRoleBinding"
  apiVersion: "rbac.authorization.k8s.io/v1"
  groupNames: null
  metadata:
    name: "system:ldap-group-syncers"
  roleRef:
    kind: "ClusterRole"
    name: "ldap-group-syncer"
  subjects:
  - kind: "ServiceAccount"
    name: "${JOB_SERVICE_ACCOUNT}"
    namespace: "${NAMESPACE}"
  userNames:
  - "system:serviceaccount:${NAMESPACE}:${JOB_SERVICE_ACCOUNT}"
- kind: "ConfigMap"
  apiVersion: "v1"
  metadata:
    name: "${LDAP_SYNC_CONFIGMAP}"
    namespace: "${NAMESPACE}"
  data:
    ldap-group-sync.yaml: |
      kind: "LDAPSyncConfig"
      apiVersion: "v1"
      url: "${LDAP_URL}"
      insecure: false
      bindDN: "${LDAP_BIND_DN}"
      bindPassword:
        file: "${LDAP_CONFIG_VOLUME_PATH}/${LDAP_BIND_PASSWORD_FILENAME}"
      ca: "${LDAP_CONFIG_VOLUME_PATH}/${LDAP_CA_FILENAME}"
      rfc2307:
        groupsQuery:
          baseDN: "${LDAP_GROUPS_SEARCH_BASE}"
          scope: "sub"
          derefAliases: "never"
          filter: "${LDAP_GROUPS_FILTER}"
          pageSize: 0
        groupUIDAttribute: "${LDAP_GROUP_UID_ATTRIBUTE}"
        groupNameAttributes: ${LDAP_GROUP_NAME_ATTRIBUTES}
        groupMembershipAttributes: ${LDAP_GROUP_MEMBERSHIP_ATTRIBUTES}
        usersQuery:
          baseDN: "${LDAP_USERS_SEARCH_BASE}"
          scope: "sub"
          derefAliases: "never"
          pageSize: 0
        userNameAttributes: ${LDAP_USER_NAME_ATTRIBUTES}
        userUIDAttribute: "${LDAP_USER_UID_ATTRIBUTE}"
        tolerateMemberNotFoundErrors: true
        tolerateMemberOutOfScopeErrors: true
    whitelist.txt: "${LDAP_GROUPS_WHITELIST}"
- kind: "CronJob"
  apiVersion: "batch/v1beta1"
  metadata:
    name: "${JOB_NAME}"
    namespace: "${NAMESPACE}"
  spec:
    schedule: "${SCHEDULE}"
    concurrencyPolicy: "Forbid"
    successfulJobsHistoryLimit: "${{SUCCESS_JOBS_HISTORY_LIMIT}}"
    failedJobsHistoryLimit: "${{FAILED_JOBS_HISTORY_LIMIT}}"
    jobTemplate:
      metadata:
        labels:
          cronjob-name: "${JOB_NAME}"
      spec:
        backoffLimit: 0
        template:
          metadata:
            labels:
              cronjob-name: "${JOB_NAME}"
          spec:
            containers:
            - name: "${JOB_NAME}"
              image: "${IMAGE}:${IMAGE_TAG}"
              command:
              - "/bin/bash"
              - "-c"
              - oc adm groups sync --confirm
                --sync-config=${LDAP_CONFIG_VOLUME_PATH}/ldap-group-sync.yaml
                $([ -s ${LDAP_CONFIG_VOLUME_PATH}/whitelist.txt ] && echo --whitelist=${LDAP_CONFIG_VOLUME_PATH}/whitelist.txt)
              volumeMounts:
              - mountPath: "${LDAP_CONFIG_VOLUME_PATH}/ldap-group-sync.yaml"
                name: "ldap-sync-config"
                subPath: "ldap-group-sync.yaml"
              - mountPath: "${LDAP_CONFIG_VOLUME_PATH}/whitelist.txt"
                name: "ldap-sync-config"
                subPath: "whitelist.txt"
              - mountPath: "${LDAP_CONFIG_VOLUME_PATH}/${LDAP_CA_FILENAME}"
                name: "ldap-sync-ca"
                subPath: "${LDAP_CA_FILENAME}"
              - mountPath: "${LDAP_CONFIG_VOLUME_PATH}/${LDAP_BIND_PASSWORD_FILENAME}"
                name: "ldap-bind-password"
                subPath: "${LDAP_BIND_PASSWORD_FILENAME}"
            volumes:
            - name: "ldap-sync-config"
              configMap:
                name: "${LDAP_SYNC_CONFIGMAP}"
            - name: "ldap-sync-ca"
              configMap:
                name: "${LDAP_CA_CONFIGMAP}"
            - name: "ldap-bind-password"
              secret:
                secretName: "${LDAP_BIND_PASSWORD_SECRET}"
            restartPolicy: "Never"
            terminationGracePeriodSeconds: 30
            activeDeadlineSeconds: 500
            dnsPolicy: "ClusterFirst"
            serviceAccountName: "${JOB_SERVICE_ACCOUNT}"
            serviceAccount: "${JOB_SERVICE_ACCOUNT}"
parameters:
- name: "NAMESPACE"
  displayName: "Namespace"
  description: "Name of the Namespace where to deploy the Scheduled Job"
  value: "openshift-config"
  required: true
- name: "JOB_NAME"
  displayName: "Job Name"
  description: "Name of the Scheduled Job to Create."
  value: "ldap-group-sync"
  required: true
- name: "SCHEDULE"
  displayName: "Cron Schedule"
  description: "Cron Schedule to Execute the Job"
  value: "@hourly"
  required: true
- name: "JOB_SERVICE_ACCOUNT"
  displayName: "Service Account Name"
  description: "Name of the Service Account To Exeucte the Job As."
  value: "ldap-group-syncer"
  required: true
- name: LDAP_CA_CONFIGMAP
  description: Name of the ConfigMap containing the LDAP Certificate Authority
  value: ldap-tls-ca
  required: true
- name: BIND_PASSWORD_SECRET
  description: Name of the Secret containing the LDAP bind password
  value: ldap-bind-password
  required: true
- name: LDAP_CONFIG_VOLUME_PATH
  description: Mount path of LDAP configuration files
  value: "/ldap-sync"
  required: true
- name: LDAP_CA_FILENAME
  description: Name of the LDAP CA file
  value: ca.crt
  required: true
- name: LDAP_BIND_PASSWORD_FILENAME
  description: Name of the LDAP bind password file
  value: bindPassword
  required: true
- name: "LDAP_GROUPS_SEARCH_BASE"
  displayName: "Group search query"
  description: "Location in LDAP tree where you will find groups"
  required: true
- name: "LDAP_GROUPS_FILTER"
  displayName: "Group Filter"
  description: "LDAP Filter to use when deciding which groups to sync into OpenShift"
  required: true
  value: "(objectClass=groupofnames)"
- name: "LDAP_GROUP_NAME_ATTRIBUTES"
  displayName: "Group name attributes"
  description: "The attribute list to use to discover the name for the group."
  required: true
  value: >-
    ["cn"]
- name: "LDAP_GROUP_MEMBERSHIP_ATTRIBUTES"
  displayName: "Group membership attributes"
  required: true
  value: >-
    ["member"]
- name: "LDAP_GROUP_UID_ATTRIBUTE"
  displayName: "Group UID Attribute"
  description: "The attribute that uniquely identifies a group on the LDAP server."
  required: true
  value: "dn"
- name: "LDAP_GROUPS_WHITELIST"
  displayName: "LDAP sync whitelist"
  description: "File content for groups sync --whitelist option"
  required: true
- name: "LDAP_URL"
  displayName: "LDAP Server URL"
  description: "URL of you LDAP server"
  required: true
- name: "LDAP_BIND_DN"
  displayName: "LDAP Bind User's DN"
  description: "The Full DN for the user you wish to use to authenticate to LDAP"
  required: true
- name: "LDAP_USERS_SEARCH_BASE"
  displayName: "User search query"
  description: "Location in LDAP tree where you will find users"
  required: true
- name: "LDAP_SYNC_CONFIGMAP"
  displayName: "LDAP sync config map"
  description: "Name for the config map storing the group sync config"
  value: "ldap-group-sync"
- name: "LDAP_USER_UID_ATTRIBUTE"
  displayName: "User UID attribute"
  description: "The attribute that uniquely identifies a user on the LDAP server."
  required: true
  value: "dn"
- name: "LDAP_USER_NAME_ATTRIBUTES"
  displayName: "User name attributes"
  description: "JSON list of attributes to use to discover the user name for group membership"
  required: true
  value: >-
    ["uid"]
- name: "LDAP_BIND_PASSWORD_SECRET"
  displayName: "LDAP Bind Password Secret"
  description: "The name for the secret in which to store the bind password"
  value: "ldap-bind-password"
  required: true
- name: "SUCCESS_JOBS_HISTORY_LIMIT"
  displayName: "Successful Job History Limit"
  description: "The number of successful jobs that will be retained"
  value: "5"
  required: true
- name: "FAILED_JOBS_HISTORY_LIMIT"
  displayName: "Failed Job History Limit"
  description: "The number of failed jobs that will be retained"
  value: "5"
  required: true
- name: "IMAGE"
  displayName: "Image"
  description: "Image to use for the container."
  required: true
  value: "registry.redhat.io/openshift4/ose-cli"
- name: "IMAGE_TAG"
  displayName: "Image Tag"
  description: "Image Tag to use for the container."
  required: true
  value: "4.1"
- name: "LDAP_SYNC_CONFIGMAP"
  displayName: "LDAP sync config map"
  description: "Name for the config map storing the group sync config"
  value: "ldap-group-sync"
- name: "LDAP_CA_CONFIGMAP"
  displayName: "LDAP sync certificate authority config map"
  description: "Name for the config map storing the TLS certificate authority"
  value: "ldap-tls-ca"
